#!/usr/bin/env bash
#
# Write the two generated nginx files for a TLS-enabled server:
# ssl.conf (the site on 443) and adminer.conf (the database panel on 8443).
#
# Called by enable-ssl.sh once the certificate exists, and again by update.sh
# on every deploy where a certificate is already there — so an improvement to
# the shared site body (site.inc) or to these two templates reaches a running
# server without anybody re-running the certificate step. The files are
# regenerated only; nothing here touches certbot.
#
#   deploy/nginx/write-ssl.sh feranocar.com
#
set -euo pipefail

DOMAIN="${1:?domain}"
NGINX="$(cd "$(dirname "$0")" && pwd)"

cat > "$NGINX/ssl.conf" <<SSLCONF
# Generated by deploy/nginx/write-ssl.sh — do not edit; it is rewritten on
# every deploy while a certificate exists. The site itself is in site.inc.

server {
    listen 443 ssl;
    # Standalone \`http2\` needs nginx 1.25+; docker-compose pins 1.27.
    http2 on;
    server_name $DOMAIN www.$DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    # Mozilla's «intermediate» list: forward secrecy only, no CBC. TLS 1.3
    # picks its own suites and ignores this line; it is here for 1.2 clients.
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    # Session tickets are encrypted with a key nginx rotates only on restart;
    # without them, resumption still works through the cache above and a
    # leaked ticket key cannot decrypt recorded traffic.
    ssl_session_tickets off;

    # Every location, header, limit and trap — the same file the HTTP server
    # includes, so the two cannot drift apart.
    include /etc/nginx/conf.d/site.inc;
}
SSLCONF

# The database panel on TLS: three locks (Basic Auth, Adminer's own login,
# the rate limit) and the same security headers as the site.
cat > "$NGINX/adminer.conf" <<ADMCONF
# Generated by deploy/nginx/write-ssl.sh. See the repository copy for the
# reasoning behind each layer; this is the same file with TLS turned on.

limit_req_zone \$binary_remote_addr zone=dbpanel:1m rate=10r/m;
limit_conn_zone \$binary_remote_addr zone=dbpanel_conn:1m;

server {
    listen 8443 ssl;
    http2 on;
    server_name $DOMAIN www.$DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_tickets off;

    server_tokens off;
    limit_req zone=dbpanel burst=30 nodelay;
    limit_conn dbpanel_conn 10;

    auth_basic "Database";
    auth_basic_user_file /etc/nginx/conf.d/.htpasswd;

    # Optional: if your own connection has a stable address, uncomment and
    # set it — then even the password prompt is unreachable from elsewhere.
    # allow 5.112.0.0/16;
    # deny all;

    location / {
        include /etc/nginx/conf.d/security-headers.inc;
        proxy_pass http://adminer:8080;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
        client_max_body_size 64m;
    }
}
ADMCONF

echo "→ wrote ssl.conf and adminer.conf for $DOMAIN"
